theme: minima
title: ğŸ¨ Paintings by a Mother-to-Be ğŸ¤°ğŸ»
description: These are original paintings by my wife â€” an incredibly creative soul and a soon-to-be mom. As we prepare to welcome a new life into our home, weâ€™re making space in our apartment and raising a bit of money to get some things for the baby.
collections:
  paintings:
    output: true